apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: james-w-lbg-node-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
